---
- name: checking if npm installed 
  shell: "bash -lc 'source $HOME/.nvm/nvm.sh && npm --version'"
  register: npm_check
  failed_when: false

- name: checking installing yarn
  shell: "bash -lc 'source $HOME/.nvm/nvm.sh && npm install --global yarn'"
  become_user: "{{ nvm_user }}"
  failed_when: false
  when: npm_check.rc==0

- name : debug message
  ansible.builtin.debug:
    msg: first install node to install yarn
  when: npm_check.rc!=0