---
- name: Running playbook to configuring the server for lms
  hosts: server
  become: true
  roles:
    - rvm_install
    - rvm_requirments
    - ruby_install
    - nvm_install
    - node_install
    - yarn_install
    - pg_devel_install

  vars:
    user: "yabx"
    ruby_version: "3.3.5"
    node_version: 16
    # node_version : 12.14.1
    


