---
- name: Install required dependencies (curl, build-essential)
  ansible.builtin.yum:
    name:
      - curl
    state: present

- block :
  - name: Ensure NVM is available
    ansible.builtin.command: "bash -c 'source ~/.nvm/nvm.sh && nvm --version'"
    register: nvm_check
    changed_when: false
    failed_when: nvm_check.rc != 0

  - name: "Install Node.js {{ node_version }}"
    ansible.builtin.command: "bash -c 'source $HOME/.nvm/nvm.sh && nvm install {{node_version}}'"
    when: nvm_check.rc == 0

  - name: "Set the default Node.js version {{ node_version }}"
    ansible.builtin.command: "bash -c 'source $HOME/.nvm/nvm.sh && nvm alias default {{node_version}}'"
    when: nvm_check.rc == 0
  become_user: "{{ user }}"


