---
- name: Install required dependencies (curl, build-essential)
  package:
    name:
      - curl
      - build-essential
    state: present
- block :
  - name: Ensure NVM is available
    command: "bash -c 'source ~/.nvm/nvm.sh && nvm --version'"
    register: nvm_check
    changed_when: false
    failed_when: nvm_check.rc != 0

  - name: "Install Node.js {{node_version}}"
    command: "bash -c 'source ~/.nvm/nvm.sh && nvm install {{node_version}}'"
    when: nvm_check.rc == 0

  - name: "Set the default Node.js version {{node_version}}"
    command: "bash -c 'source ~/.nvm/nvm.sh && nvm alias default {{node_version}}'"
    when: nvm_check.rc == 0

  - name: Verify Node.js installation
    command: "bash -c 'source ~/.nvm/nvm.sh && node --version'"
    register: node_version
    changed_when: false

  - name: Display Node.js version
    debug:
      msg: "Installed Node.js version: {{ node_version.stdout }}"
  become_user: "{{project_user}}"